[package]
name = "gears-cli"
version = "0.1.12"
authors = ["Michiel Kalkman <michiel@nosuchtype.com>"]
description = "Gears CLI tool"
documentation = "https://docs.rs/xflow"
homepage = "https://github.com/gears-project/gears-cli"
repository = "https://github.com/gears-project/gears-cli.git"
readme = "README.md"
keywords = ["gears"]
categories = []
license = "MIT"
build = "build.rs"

[dependencies]
gears = "0.1.7"
actix-web-middleware-opa = { version = "0.1.1", default-features = false }
log = "0.4"
env_logger = "0.6"
rustyline = "4.0"
actix = "0.8"
actix-web = { version = "0.7",  default-features = false }
futures = "0.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
bytes = { version = "0.4", features = ["serde"] }
uuid = { version = "0.7", features = ["serde", "v4"] }
jsonapi = "*"

[dependencies.clap]
version = "~2.33.0"
default-features = false
features = [ "suggestions", "color", "wrap_help" ]

[build-dependencies]
peg = { version = "0.5" }

[replace]
# actix-web-middleware-opa = { path = "/home/michiel/dev/github/actix-web-middleware-opa" }
# "gears:0.1.6" = { path = "/home/michiel/dev/gears-project/gears-core-rust" }
# "gears:0.1.6" = { git = 'https://github.com/gears-project/gears-core-rust' }

[package.metadata.deb]
maintainer = "Michiel Kalkman <michiel@nosuchtype.com>"
copyright = "2018, Michiel Kalkman <michiel@nosuchtype..com>"
license-file = ["LICENSE", "4"]
extended-description = """\
Gears CLI tool
"""
depends = "$auto"
section = "utility"
priority = "optional"
assets = [
    ["target/release/gears-cli", "usr/bin/", "755"],
    ["README.md", "usr/share/doc/gears-cli/README", "644"],
]
